### ISSUE TITLE
[PnP]Benchmark tests plan CheckList

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#361]
Track the Benchmark test tasks (step 1 of 3)

- [x] Add parameters for the command line @minggangw
     - done by #360 
- [x] Pre-gen when installing  @minggangw
     - done by #357
- [x]  Add Startup time test  @minggangw
     - done by #363 
- [ ]  Performance of different messages  @minggangw
     - `sensor_msgs/PointCloud2` and `sensor_msgs/CompressedImage` with the current    `std_msgs/UInt8MultiArray`
- [ ]  Auto script @hanyia
- [ ] Auto report/chart generation @kenny-y 
- [x]  The maximum data capacity  @hanyia
- [x] Make sure every language is with best optimization @minggangw
     - `rclpy` & `rclcpp` GCC with flags `-Wall -Wextra -Wpedantic -fPIC   -std=gnu++14`
     - `rclnodejs` GCC with flags `-fPIC  -Wall -Wextra -Wno-unused-parameter -m64 -fstack-protector-strong -fPIE  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security  -fno-omit-frame-pointer -fno-rtti  -std=c++14`

**Comment by minggangw** [comment]
@hanyia @kenny-y I created this issue to track our target of the benchmark test.

**Comment by hanyia** [comment]
Till now, based on our testing, about 250000KB is the maximum capacity of C++/Node.js client and 200000KB as Python(subscription/publisher samples).

**Comment by minggangw** [comment]
>Auto script @hanyia
Auto report/chart generation @kenny-y

As these two items have finished and we have fixed some critical bugs during these days, hopefully we will have the release to be published recently, which will build against the latest master branch of ROS 2.0
