### ISSUE TITLE
Actions support in rclnodejs

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#469]

**Comment by minggangw** [comment]
I spent half a day to dig into this feature and found it's more difficult than I thought which means we need more effort on it. An official [introduction](https://index.ros.org/doc/ros2/Tutorials/Understanding-ROS2-Actions/) of Actions in ROS2

**Comment by mattrichard** [comment]
Here's a breakdown of the work that needs to be done.

- [x] Add actions to event loop (#570)
- [x] Read action type support libraries (#571)
- [x] Update message generation to properly handle .action files (#577)
- [x] Add all action binding methods for rcl integration (#596)
- [x] Add new ActionClient and ActionServer classes (#596)
- [x] Integrate action clients/servers into node handle execution (#596)
- [x] Unit/integration testing (#596)
- [x] Action graph functions (#611)
- [x] Update TypeScript typings (#616)
- [x] Documentation and examples (#596, #615)
- [x] Relax and enjoy (#630)
