### ISSUE TITLE
Node v12

### ISSUE THREAD

**Issue by mattrichard** [RobotWebTools/rclnodejs#568]
rclnodejs should always support the active and maintenance LTS versions of Node.js. Supporting the current version too would be a big plus. Node v12 has been in active LTS for a few months now and should be supported for easier adoption of rclnodejs in newer projects. This issue is to track the changes needed to support v12.

Changes required.

- [x] Fix v8 deprecation warnings (#567)
- [x] Address ref incompatibility. Alternatives mentioned in #527. (#578)
- [x] Fix new issues with ToString, etc. (#582)
- [x] Update CI to use NodeJS 12 (#527)
